networkmap:Reader Flats Apartments main
	g++ Reader.o Flats.o Apartments.o main.o -o networkmap
Reader:
	g++ -std=c++11 -c Reader.cpp -o Reader.o
Flats:
	g++ -std=c++11 -c Flats.cpp -o Flats.o
Apartments:
	g++ -std=c++11 -c Apartments.cpp -o Apartments.o
main:
	g++ -std=c++11 -c main.cpp -o main.o
	
	

